name: 'Microblog'
description: 'Create a microblog from Github issues'
inputs:
  repo-token:
    description: 'Github Access Token'
    required: true
  url:
    description: 'Full site URL including base path if it exists.'
    required: true
  title:
    description: 'Title of the Microblog'
    required: false
  description:
    description: 'Description of the Microblog'
    required: false
  theme:
    description: 'Theme of the Microblog'
    required: false
  max-width:
    description: 'Max width of the content area in px'
    required: false
    default: 640
  date-format:
    description: 'Date format based on https://date-fns.org/v2.10.0/docs/format'
    required: false
    default: 'd.M.yyyy H:mm'
  posts-per-page:
    description: 'Amount of posts per page'
    required: false
    default: 10
runs:
  using: 'node12'
  main: 'dist/index.js'
